version: "3.8"

services:
  beat-motivator:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-env:
    build: node-env
    image: node-custom
    container_name: node-env
    tty: true
    volumes:
      - .:/app
